remote_theme: ddc-java/ddc-dav

title: Codebreaker
description: A code-breaking solitaire puzzle game.

author:
  name: Royce Reano
  copyright: false

page_navigator:
  enabled: true

titles_from_headings:
  enabled: false
